### ISSUE TITLE
Hour in timeline out of order

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#246] opened 2016-05-05 11:24 UTC
![captura de tela 2016-05-05 as 12 23 26](https://cloud.githubusercontent.com/assets/28031/15042490/3eabf082-12bc-11e6-8c08-dd7bfd05258e.png)

**Comment by brunosiqueira** [comment] 2016-05-25 02:08
Still something weird
![captura de tela 2016-05-24 as 23 07 46](https://cloud.githubusercontent.com/assets/28031/15525930/5d089f9c-2204-11e6-8d44-2e94056d2e3a.png)

**Comment by dborkan** [comment] 2016-05-25 11:58
OK - I'm able to replicate now on the dev server with the admin group for 5/5/16, will fix

**Comment by dborkan** [comment] 2016-05-31 17:57
Found the problem here: https://github.com/igarape/copcast-admin/blob/webrecorder/src/app/history/timeline/segments.directive.js#L106

The issue is that we are using .keys() on a Map object (same as ```Object.keys(...)```), and assuming the keys will be sorted in the order we want.  However JavaScript doesn't guarantee the ordering.  For example:
```
x = {'02': 1, '03': 1, '04': 1, '11': 123};
a = Object.keys(x);
```
after this a will be ```["11", "02", "03", "04"]``` (11 is first, even though it was added last to the map).

The solution here is just to change our calls to ```x.keys()``` to ```x.keys().sort()```

**Comment by dborkan** [comment] 2016-05-31 20:23
Actually it's a little worse than my previous comment suggests - there is also a problem that we have ng-repeat statement which iterate over maps, expecting the keys to be in sorted order, e.g. https://github.com/igarape/copcast-admin/blob/webrecorder/src/app/history/timeline/segments.html#L25

As per angular docs the ordering for this is undefined (https://docs.angularjs.org/api/ng/directive/ngRepeat).  I'm going to try to make the ng-repeat statements interate over an array instead, which will be sorted by time

**Comment by dborkan** [comment] 2016-05-31 21:10
Fix for this is in https://github.com/igarape/copcast-admin/pull/276

**Closed** 2016-06-01 02:00 UTC
Labels: bug, History, in progress
